### ISSUE TITLE
Criar script para montagem de ambiente de desenvolvimento

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/GOG#3]
Definir e implementar script para montagem simplificada de container para desenvolvimento. Docker e Vagrant são duas possibilidades. O objetivo é facilitar a montagem de ambiente de desenvolvimento independente de plataforma.

**Comment by clelsonsalles** [comment]
Tarefa finalizada.
Foi criado o repositório https://github.com/culturagovbr/docker-GOG, contendo as informações necessárias para utilizar o Docker no projeto GOG
