### ISSUE TITLE
Mensagem de manifestação sendo recebido incorretamente

### ISSUE THREAD

**Issue by moisesrlima** [culturagovbr/GOG#36]
Recebi um email informando que a aplicação "Ouvidoria" está disparando mensagem para usuários administradores do Ouvidoria através do email "naoresponda.ouvidoria@videira.sc.gov.br".

Favor verificar se esse email faz parte da aplicação da Ouvidoria do MinC.

Prezado Moises,
 
                O servidor Thadeu também recebeu email de cobrança “ Ouvidoria Videira”
 
Atenciosamente,
OUVIDORIA - OUV/GM/MINC
Coordenação de Atendimento e Acesso à Informação
Esplanada dos Ministérios, Bloco B, 3º Andar
CEP: 70068-900 - Brasília/DF
E-mail: sic@cultura.gov.br / ouvidoria@cultura.gov.br
Telefone: +55 (0XX61) 2024-2317 / 2024-2245
Você conhece a Carta de Serviços ao Cidadão do MinC? Acesse
http://www.cultura.gov.br/documents/10883/1433812/carta-servicos-2017-2.pdf/7592302d-f23e-4e5e-8fae-5bd7cf34f839
 
De: Thadeu Costa Normando [mailto:thadeu.normando@cultura.gov.br] 
Enviada em: segunda-feira, 4 de setembro de 2017 10:44
Para: Ouvidoria do Ministerio da Cultura
Assunto: ENC: [MinC Ouvidoria] - Nova mensagem - 2017000027
 
 
 
Atenciosamente,
THADEU C. NORMANDO
Coordenador de Atendimento e Acesso à Informação
OUVIDORIA / GM / MINISTÉRIO DA CULTURA
Telefone: +55(0xx61) 2024-2032
De: Ouvidoria Videira [mailto:naoresponda.ouvidoria@videira.sc.gov.br] 
Enviada em: sexta-feira, 1 de setembro de 2017 18:09
Para: Teste <thadeu.normando@cultura.gov.br>
Assunto: [MinC Ouvidoria] - Nova mensagem - 2017000027
 
Ouvidoria Ministério da Cultura
 
Prezado (a) colaborador (a),
Existe uma nova mensagem direcionada à sua Unidade, no sistema da Ouvidoria, de n° 2017000027.
Para entrar no sistema, acesse http://ouvidoria.cultura.gov.br/ouvidoria/ 

Atenciosamente,
Ouvidoria
Ministério da Cultura
 
Mensagem enviada pelo sistema de Ouvidoria do Ministério da Cultura. Favor não responder diretamente a este e-mail.

**Comment by vinnyfs89** [comment]
<div>
<div>Prezado,</div>
<div></div>
<div>Identificamos que o e-mail de origem &eacute; "<a href="mailto:naoresponda.ouvidoria@videira.sc.gov.br" target="_blank" style="color: #954f72; text-decoration: underline; font-family: Calibri, sans-serif; font-size: 14.6667px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;">naoresponda.ouvidoria@videira.sc.gov.br</a>" o qual aparentemente n&atilde;o faz parte do dom&iacute;nio do MINC.</div>
<div></div>
<div>Para que possamos confirmar essa informa&ccedil;&atilde;o solicitamos que a equipe de banco de dados consulte na tabela&nbsp;<span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><strong>TbPreferenciaSistema </strong>e verifique se o e-mail mencionado acima consta nessa tabela. A tabela&nbsp;<span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><a href="https://github.com/culturagovbr/GOG/blob/eb1a47f5df53555c0235dc1231a50b6cd5a7ee94/documentacao/arquitetura.md"><strong>TbPreferenciaSistema</strong></a> &eacute; utilizada pela aplica&ccedil;&atilde;o para fazer o envio de <a href="https://github.com/culturagovbr/GOG/blob/eb1a47f5df53555c0235dc1231a50b6cd5a7ee94/documentacao/MontarAmbienteDesenvolvimento_CargaInicialDados.md">e-mails</a>. </span></span></span></div>
<div><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span></span></span></div>
<div><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span style="color: #000000; font-family: arial, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Caso o e-mail conste na nossa base de dados quer dizer que o e-mail foi disparado atrav&eacute;s da nossa aplica&ccedil;&atilde;o, sen&atilde;o provavelmente tenha sido disparada &agrave; partir de outra aplica&ccedil;&atilde;o que foi criada &agrave; partir de algum fork do nosso reposit&oacute;rio:&nbsp;<strong>https://github.com/culturagovbr/GOG</strong></span></span></span>
<div style="clear: both;"></div>
</div>
<div></div>
<div></div>
<div></div>
</div>

**Comment by heronbonfim** [comment]
Prezado Vinícius,

A tabela TbPreferenciaSistema do sistema de ouvidoria do Ministério da Cultura utiliza o e-mail: 
naoresponda.ouvidoria@cultura.gov.br.

Att,

Heron Bonfim

**Comment by vinnyfs89** [comment]
Bacana, Heron.

Então para esse cenário acredito que o usuário que o acionou deve estar cadastrado em uma outra aplicação criada à partir desse repositório, porém não devem ter modificado a url de redirecionamento para quando uma nova manifestação é cadastrada.
