### ISSUE TITLE
Isso já existe

### ISSUE THREAD

**Issue by uira** [culturagovbr/GOG#6]
Chama http://alaveteli.org/

**Comment by clelsonsalles** [comment]
O sistema GOG é uma implementação específica, desenvolvida internamente pela equipe da CGTI do MinC. As funcionalidades implementadas atendem especificidades de negócio que extrapolam o escopo funcional de outros sistemas de ouvidoria.
Para os nossos usuários internos a vantagem será a manutenção das funcionalidades específicas atendidas hoje pelo nosso sistema, dentre as quais podemos citar, para exemplificar, o trâmite e tratamento das manifestações pelas áreas ou unidades envolvidas.

**Comment by uira** [comment]
Você chegou a dar uma olhada no Alaveteli?

Pq ele tem tudo isso e muuuuito mais.
